### ISSUE TITLE
Unable to activate fcitx in Emacs

### ISSUE THREAD

**Issue by x-ji** [cute-jumper/fcitx.el#19]
I'm not sure whether this is a bug related to this package or Emacs itself, but since I've found this package, I'd like to post here for help.

I have never been able to get fcitx working in Emacs, though it works normally in other apps. I've read some blog posts on this topic, for example http://blog.fourcels.me/2015/11/11/emacs-support-fcitx.html and http://www.cnblogs.com/pylemon/archive/2012/01/05/2312682.html, but their method (set LC_CTYPE to zh_CN.UTF-8) didn't seem to help. After installing this package in Spacemacs, fcitx seems to be still not activated either.

Since I've found multiple posts on this topic, it must be a pretty commonplace issue. I'd like to know whether anybody has heard of it on Ubuntu and how they solved it, if applicable. I'm currently on Ubuntu 16.04 LTS with `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17 on lgw01-04, modified by Debian`. Thanks in advance.

**Comment by cute-jumper** [comment]
I believe this issue is nothing to do with this package.  I'm using Arch Linux myself and my solution is `LC_CTYPE=zh_CN.utf-8 emacs`, which you've already found out. I think the issue should be related to your own environment setup and I'm afraid I can't help you about this. Trying to post this issue to [here](https://github.com/fcitx/fcitx) may be a better choice.
