### ISSUE TITLE
Doesn't work in evil-emacs-state

### ISSUE THREAD

**Issue by zilongshanren** [cute-jumper/fcitx.el#6]
Because many minor mode keybindings will be override by evil-insert-state.

When evil enter evil-insert-state , I change it to emacs state.

And I like the original Emacs key bindings (c-n/c-p/c-a etc) for editing text.

**Comment by zilongshanren** [comment]
I copied the original implementation and add it to my config:

```
      (defun zilongshanren/fcitx-evil-turn-on ()
        (interactive)
        (eval-after-load "evil"
          '(progn
             (add-hook 'evil-emacs-state-exit-hook
                       #'fcitx--evil-insert-maybe-deactivate)
             (add-hook 'evil-emacs-state-entry-hook
                       #'fcitx--evil-insert-maybe-activate)
             (if (fboundp 'advice-add)
                 (progn
                   (advice-add 'switch-to-buffer :around
                               #'fcitx--evil-switch-buffer)
                   (advice-add 'other-window :around
                               #'fcitx--evil-switch-buffer))
               (ad-enable-advice 'switch-to-buffer 'around 'fcitx--evil-switch-buffer-1)
               (ad-activate 'switch-to-buffer)
               (ad-enable-advice 'other-window 'around 'fcitx--evil-switch-buffer-2)
               (ad-activate 'other-window)))))
      (zilongshanren/fcitx-evil-turn-on)

```

**Comment by cute-jumper** [comment]
Currently `fcitx.el` doesn't work with `evil-emacs-state`. The reason is that when I use evil, I usually use Emacs key bindings in `evil-insert-state`. This is what I do:

    (setcdr evil-insert-state-map nil)
    (define-key evil-insert-state-map [escape] 'evil-normal-state)

I don't actually need to enter `evil-emacs-state`(Anyway, pessing "i" is easier than "C-z"!). Maybe this can be a workaround for you too.

If you don't like this, in fact, we can also add support for `evil-emacs-state`, but some information needs to be saved. For example, it is possible for the user to switch from `evil-insert-state` to `evil-emacs-state`. In this case, we don't actually need to change the status of fcitx. It is not hard to only implement this functionality, but I guess this would also affect some code related to the prefix key feature. I may try to implement this later, but if you've figured out how to do it, please consider creating a pull request. Any contributions are always welcome!

Side note: I don't use `evil` now. Since most of the time I only use some simple features of `evil`, I use [hydra](https://github.com/abo-abo/hydra) to emulate a simple vi-like mode.

**Comment by zilongshanren** [comment]
@cute-jumper 
Thanks for the idea to disable all the key bindings in evil-insert-state. 

I don't need to manually change `evil-insert-state` to `evil-emacs-state`, here is what I do:

```
      (defadvice evil-insert-state (around zilongshanren/holy-mode activate)
        "Preparing the holy water flasks."
        (evil-emacs-state))

      (define-key evil-emacs-state-map [escape] 'evil-normal-state)

```

I also installed hydra, I only use it for showing some major mode keybindings, but I can't live without evil/leader key. I'm using Spacemacs at the moment, so evil/leader key is very useful.

**Comment by cute-jumper** [comment]
Is there any benefit by using `defadvice`? I'm not familiar with evil internals, but I think an easier way to achieve the same goal is:

    (define-key evil-normal-state-map "i" 'evil-emacs-state)

I just tested your code(and I use <kbd>i</kbd> to enter `evil-emacs-state` as I said above). Here is what I did:
1. Enable fcitx in `evil-emacs-state`
2. Press <kbd>ESC</kbd> to enter `evil-normal-state`. Fcitx is disabled now.
3. Press <kbd>i</kbd> to enter `evil-emacs-state`. Fcitx is re-enabled.

It seems `fcitx.el` actually works in this case.

Do you mean that it fails in some other cases?

**Comment by cute-jumper** [comment]
Maybe it would be better to use the entry hook and exit hook of `evil-normal-state` instead of `evil-insert-state` or `evil-emacs-state`(I haven't tried though). What do you think? And how does `fcitx.el` fail in your case?

**Comment by zilongshanren** [comment]
@cute-jumper  
`fcitx.el` is working in my side now. 

I use defadvice only for turning to `evil-emacs-state` automatically when I press `i` or `a`.

And the `evil-emacs-state-exit-entry` is working with my setup.

Thanks again for writing the awesome fcitx.el.
